webtalk_init -webtalk_dir /home/INTRA/raogbe/workspace/soc-audio-mixer/vivado/step1/step1.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May 20 13:57:59 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174123256_177724473_177724475_422" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "jgsdlsvqokag2ithfn95r4s5j0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.1_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "SUSE LINUX" -context "user_environment"
webtalk_add_data -client project -key os_release -value "openSUSE Leap 42.1 (x86_64)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3470T CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2193.464 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1463739914000" -context "sdk\\\\hardware/1463739914000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1463739914000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1463739914000"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.1" -context "sdk\\\\hardware/1463739914000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1463739914000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1463739914000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1463739914000"
webtalk_add_data -client sdk -key uid -value "1463739943000" -context "sdk\\\\bsp/1463739943000"
webtalk_add_data -client sdk -key hwid -value "1463739914000" -context "sdk\\\\bsp/1463739943000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1463739943000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1463739943000"
webtalk_add_data -client sdk -key uid -value "1463739958000" -context "sdk\\\\application/1463739958000"
webtalk_add_data -client sdk -key hwid -value "1463739914000" -context "sdk\\\\application/1463739958000"
webtalk_add_data -client sdk -key bspid -value "1463739943000" -context "sdk\\\\application/1463739958000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1463739958000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1463739958000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1463739958000"
webtalk_transmit -clientid 1106928471 -regid "174123256_177724473_177724475_422" -xml /home/INTRA/raogbe/workspace/soc-audio-mixer/vivado/step1/step1.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/INTRA/raogbe/workspace/soc-audio-mixer/vivado/step1/step1.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/INTRA/raogbe/workspace/soc-audio-mixer/vivado/step1/step1.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
