# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/INTRA/rauno.padari/workspace/audio-mixer/ip_repo/zedboard_audio/constraints/zed_audio.xdc

# Block Designs: bd/audio_mixer/audio_mixer.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer || ORIG_REF_NAME==audio_mixer}]

# IP: bd/audio_mixer/ip/audio_mixer_processing_system7_0_0/audio_mixer_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_processing_system7_0_0 || ORIG_REF_NAME==audio_mixer_processing_system7_0_0}]

# IP: bd/audio_mixer/ip/audio_mixer_zed_audio_0_0/audio_mixer_zed_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_zed_audio_0_0 || ORIG_REF_NAME==audio_mixer_zed_audio_0_0}]

# IP: bd/audio_mixer/ip/audio_mixer_xlconstant_0_0/audio_mixer_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_xlconstant_0_0 || ORIG_REF_NAME==audio_mixer_xlconstant_0_0}]

# XDC: bd/audio_mixer/ip/audio_mixer_processing_system7_0_0/audio_mixer_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==audio_mixer_processing_system7_0_0 || ORIG_REF_NAME==audio_mixer_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/audio_mixer/audio_mixer_ooc.xdc
