# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/zed_audio.xdc

# Block Designs: bd/audio_mixer/audio_mixer.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer || ORIG_REF_NAME==audio_mixer}]

# IP: bd/audio_mixer/ip/audio_mixer_processing_system7_0_0/audio_mixer_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_processing_system7_0_0 || ORIG_REF_NAME==audio_mixer_processing_system7_0_0}]

# IP: bd/audio_mixer/ip/audio_mixer_zed_audio_0_0/audio_mixer_zed_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_zed_audio_0_0 || ORIG_REF_NAME==audio_mixer_zed_audio_0_0}]

# IP: bd/audio_mixer/ip/audio_mixer_processing_system7_0_axi_periph_0/audio_mixer_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==audio_mixer_processing_system7_0_axi_periph_0}]

# IP: bd/audio_mixer/ip/audio_mixer_rst_processing_system7_0_100M_0/audio_mixer_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==audio_mixer_rst_processing_system7_0_100M_0}]

# IP: bd/audio_mixer/ip/audio_mixer_audio_to_axi_0_2/audio_mixer_audio_to_axi_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_audio_to_axi_0_2 || ORIG_REF_NAME==audio_mixer_audio_to_axi_0_2}]

# IP: bd/audio_mixer/ip/audio_mixer_xlconstant_0_0/audio_mixer_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_xlconstant_0_0 || ORIG_REF_NAME==audio_mixer_xlconstant_0_0}]

# IP: bd/audio_mixer/ip/audio_mixer_axi_to_audio_0_0/audio_mixer_axi_to_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_axi_to_audio_0_0 || ORIG_REF_NAME==audio_mixer_axi_to_audio_0_0}]

# IP: bd/audio_mixer/ip/audio_mixer_xbar_0/audio_mixer_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_xbar_0 || ORIG_REF_NAME==audio_mixer_xbar_0}]

# IP: bd/audio_mixer/ip/audio_mixer_auto_pc_0/audio_mixer_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_auto_pc_0 || ORIG_REF_NAME==audio_mixer_auto_pc_0}]

# XDC: bd/audio_mixer/ip/audio_mixer_processing_system7_0_0/audio_mixer_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==audio_mixer_processing_system7_0_0 || ORIG_REF_NAME==audio_mixer_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/audio_mixer/ip/audio_mixer_rst_processing_system7_0_100M_0/audio_mixer_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==audio_mixer_rst_processing_system7_0_100M_0}]

# XDC: bd/audio_mixer/ip/audio_mixer_rst_processing_system7_0_100M_0/audio_mixer_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==audio_mixer_rst_processing_system7_0_100M_0}]

# XDC: bd/audio_mixer/ip/audio_mixer_rst_processing_system7_0_100M_0/audio_mixer_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/audio_mixer/ip/audio_mixer_xbar_0/audio_mixer_xbar_0_ooc.xdc

# XDC: bd/audio_mixer/ip/audio_mixer_auto_pc_0/audio_mixer_auto_pc_0_ooc.xdc

# XDC: bd/audio_mixer/audio_mixer_ooc.xdc
