webtalk_init -webtalk_dir /home/INTRA/rauno.padari/workspace/soc-audio-mixer/vivado/step3/step3.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 25 13:32:56 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174123256_177724473_177724475_422" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cjsdcl4odvfmmchovrrp1oaanc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.1_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "SUSE LINUX" -context "user_environment"
webtalk_add_data -client project -key os_release -value "openSUSE Leap 42.1 (x86_64)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3470T CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2337.558 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1464166403000" -context "sdk\\\\bsp/1464166403000"
webtalk_add_data -client sdk -key hwid -value "1463739914000" -context "sdk\\\\bsp/1464166403000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1464166403000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1464166403000"
webtalk_add_data -client sdk -key uid -value "1464166420000" -context "sdk\\\\application/1464166420000"
webtalk_add_data -client sdk -key hwid -value "1463739914000" -context "sdk\\\\application/1464166420000"
webtalk_add_data -client sdk -key bspid -value "1464166403000" -context "sdk\\\\application/1464166420000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1464166420000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1464166420000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1464166420000"
webtalk_transmit -clientid 1259043026 -regid "174123256_177724473_177724475_422" -xml /home/INTRA/rauno.padari/workspace/soc-audio-mixer/vivado/step3/step3.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/INTRA/rauno.padari/workspace/soc-audio-mixer/vivado/step3/step3.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/INTRA/rauno.padari/workspace/soc-audio-mixer/vivado/step3/step3.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
